# Numpy (Part -2 )
Date : 10 May 2025 <br>
Day : Saturday

In [12]:
import numpy as np

## 1.Arange 

In [13]:
# 1.Create an array of all even numbers from 10 to 30 (inclusive).
arr1 = np.arange(10,30,2)
arr1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

## 2.LinSpace

In [14]:
# 2.Generate 5 equally spaced numbers between 0 and 1, including both endpoints.
# arr2 = np.linspace(0,1,5)
arr2 = np.linspace(0,1,5,dtype=np.int64)
arr2

array([0, 0, 0, 0, 1])

In [15]:
# 3.Create an array starting from 50 down to 20, decreasing by 5 each step.

arr3 = np.arange(50,20,-5)
arr3

array([50, 45, 40, 35, 30, 25])

In [16]:
# 4.Generate 10 values between -2 and 2, and find the step size between them..
arr4 = np.linspace(-2,2,10)
arr4

array([-2.        , -1.55555556, -1.11111111, -0.66666667, -0.22222222,
        0.22222222,  0.66666667,  1.11111111,  1.55555556,  2.        ])

In [17]:
# 5.Create a list of integers from 1 to 9 using arange()
arr5 = np.arange(1,9)
arr5

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
# 6.Create a list of 7 equally spaced points between 1 and 9 using linspace()
arr6 = np.linspace(1,9,7)
arr6

array([1.        , 2.33333333, 3.66666667, 5.        , 6.33333333,
       7.66666667, 9.        ])

## 3. Sort Array

In [19]:
arr7 =np.array([12,11,9,13,14,8])
sorted_arr = np.sort(arr7)
sorted_arr

array([ 8,  9, 11, 12, 13, 14])

## 4. Concatenation

In [20]:
# for 1D array concatenation is done by using np.concatenate((array1,array2))
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array_concat = np.concatenate((array1,array2))
array_concat

array([1, 2, 3, 4, 5, 6])

In [21]:
# For 2D Arrays with Row Wise Concatenation
a = [[1, 2, 3], [4, 5, 6]]
b = [[7, 8, 9]]
c = np.concatenate((a, b), axis=0)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
# For 2D Arrays with Column Wise Concatenation
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[3,2,4],[4,2,1]])
z = np.concatenate((x,y),axis=1)
z

array([[1, 2, 3, 3, 2, 4],
       [4, 5, 6, 4, 2, 1]])

## 3D Array 

In [23]:
array3d = np.array([[[1,2,3],[4,5,6]],
                    [[1,2,3],[4,5,6]],
                    [[1,2,3],[4,5,6]]
                    ])
array3d.shape

(3, 2, 3)

In [24]:
array3d.size

18

## 5.Reshape Array

In [30]:
array3d.reshape(2,9)
array3d.shape

(3, 2, 3)

## 6.Convert 1D to 2D Array

In [34]:
arr1 = np.array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])
arr1 = arr1[np.newaxis,:]
arr1

array([[10, 12, 14, 16, 18, 20, 22, 24, 26, 28]])

##