# **Numpy Introduction**
Date : 10 May 2025 <br>Day : Saturday

## 🧠 **What is a NumPy Array?**
A NumPy array is a powerful data structure provided by the NumPy (Numerical Python) library, used in Python for numerical and scientific computing. It is known as ndarray (n-dimensional array).

## ✅ **Key Features:**
- **Multidimensional:** It can be 1D (like a list), 2D (like a matrix), or higher dimensions.

- **Homogeneous:** All elements in a NumPy array are of the same data type.

- **Faster:** More efficient than Python lists due to optimized memory storage and operations.

## Import Library

In [2]:
import numpy as np 

## 1. One Dimentional Array

In [5]:
a= np.arange(6)
print(a)

[0 1 2 3 4 5]


In [22]:
array = np.array(['Name','Competition','Codes','Rank','Discussions'])
print(array)
array.shape

['Name' 'Competition' 'Codes' 'Rank' 'Discussions']


(5,)

## 2. Two Dimentional Array

In [15]:
a2 = a[np.newaxis, :]
print(a2)
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [21]:
table = np.array([('Name','Rank','Subscribers'),('Ahmed','3+','50K'),('Abdullah','1+','500K')])
print(table)
table.shape


[['Name' 'Rank' 'Subscribers']
 ['Ahmed' '3+' '50K']
 ['Abdullah' '1+' '500K']]


(3, 3)

## 3. Three Dimentional Array 

In [17]:
a3 = a2[np.newaxis,:]
print(a3)
a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

## Data Type of Array 

In [33]:
print(f"Data of Array : {a.dtype}")
print(f"Type of Array : {type(a)}")

Data of Array : int64
Type of Array : <class 'numpy.ndarray'>


## Array Attributes 

In [39]:
# check the numpy array attributes
print(f"Array Shape : {a.shape}")
print(f"Array Dimension : {a.ndim}")    
print(f"Array Type : {type(a)}")
print(f"Array Data Type : {a.dtype}")
print(f"Array Item Size : {a.itemsize}")
print(f"Array Size : {a.size}")
print(f"Array Length : {len(a)}")
print(f"Array Data Size : {a.nbytes}")

Array Shape : (6,)
Array Dimension : 1
Array Type : <class 'numpy.ndarray'>
Array Data Type : int64
Array Item Size : 8
Array Size : 6
Array Length : 6
Array Data Size : 48


## Initialize Arrays


In [23]:
# zeros matrix (numpy array having zeros)
np.zeros((2,3)) 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# ones matrix (numpy array having ones)
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
# full array (fill all indices with the same value)
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [29]:
# identity matrix (numpy array having identity matrix)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])