# Numpy Indexing and Slicing
Date 11 May 2025<br>Day Sunday

In [1]:
import numpy as np

In [81]:
# create an array 
a = np.arange(1,8)
a

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
a[4:]

array([5, 6, 7])

In [15]:
b = np.arange(0,12,2)
b

array([ 0,  2,  4,  6,  8, 10])

In [17]:
# reshape b to be a 2D array
c= b.reshape(2,3)
c

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [19]:
c[1]

array([ 6,  8, 10])

# HStack and VStack

In [30]:
# horizontal stack two arrays 
a = np.arange(1,8)
b = np.arange(8,15)

In [33]:
c = np.hstack((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
d = np.vstack((a,b))
d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [36]:
c.reshape(2,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

---
# Matrices in Numpy

In [38]:
# create a matrix of 2*3 dimensions
a = np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [41]:
# create a matrix of big dimension
b = np.arange(0,100,2).reshape(5,10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

## Slicing Matrix

In [43]:
b[:,:] # select all rows and all columns

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [47]:
b[0:2,:] # select rows 0 and 1 and columns 0 to end

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38]])

In [42]:
b[1:3,3:5] # select rows 1 and 2 and columns 3 and 4

array([[26, 28],
       [46, 48]])

In [45]:
b[1,] # select rows 1 to end and all columns because comma shows that we want to select all columns

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

# Matrix Aggregate Function: 
max(),min(),sum(),mean()

In [57]:
print(f"Maximum value of b : {b.max()}")
print(f"Maximum value in column : {b.max(axis=1)}")
print(f"Minimum value of b : {b.min()}")
print(f"Mean value of b : {b.mean()}")
print(f"Sum of b : {b.sum()}")
print(f"Shape of b : {b.shape}")

Maximum value of b : 98
Maximum value in column : [18 38 58 78 98]
Minimum value of b : 0
Mean value of b : 49.0
Sum of b : 2450
Shape of b : (5, 10)


In [60]:
matrix = np.arange(0,20,2).reshape(5,2)
print(matrix)

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


In [64]:
matrix + np.array([20,22]) 
# You can apply subtraction, multiply , division and mode like addition

array([[20, 24],
       [24, 28],
       [28, 32],
       [32, 36],
       [36, 40]])

In [63]:
np.vstack((matrix,np.array([42,44])))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [42, 44]])

# Unique Values in Array

In [ ]:
matrix.unique()

# Transpose an Array 

In [67]:
matrix

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [66]:
transposed_matrix =matrix.T
transposed_matrix

array([[ 0,  4,  8, 12, 16],
       [ 2,  6, 10, 14, 18]])

In [72]:
transposed_matrix = matrix.transpose()
transposed_matrix

array([[ 0,  4,  8, 12, 16],
       [ 2,  6, 10, 14, 18]])

# How to Reverse/Flip an Array 
- Reverse the order of elements in an array along the given axis.

- The shape of the array is preserved, but the elements are reordered

In [69]:
arr = np.array([11,12,13,14,15])
arr

array([11, 12, 13, 14, 15])

In [71]:
reverse_array = np.flip(arr)
reverse_array

array([15, 14, 13, 12, 11])

In [77]:
# reverse 2D array 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
reverse_array = np.flip(arr,axis=0) # reverse the sequence of rows 
reverse_array

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [78]:
reverse_array = np.flip(arr,axis=1) # reverse the sequence of column 
reverse_array

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])